name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v -race ./...
      - name: Run vetting
        run: go vet

      - name: Setup Minio
        shell: bash
        run: |
          docker run -d --network host --name minio \
            -e "MINIO_ACCESS_KEY=minioadmin" \
            -e "MINIO_SECRET_KEY=minioadmin" \
            -e "MINIO_ADDRESS=:9000" \
            -v /tmp/data:/data \
            -v /tmp/config:/root/.minio \
            minio/minio:latest server /data
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go mod download

    - name: Test with the race detector
      run: GOMAXPROCS=1 go test -v -race ./...
